spring:
  application:
    name: G54-AI-Workshop
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o
          max-tokens: 1000
          temperature: 0.2
    retry:
      max-attempts: 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB